# fi_info
# Autogenerated from man page /usr/share/man/man1/fi_info.1.gz
complete -c fi_info -s n -l node --description 'interfaces.'
complete -c fi_info -s P -l port --description '.'
complete -c fi_info -s c -l caps --description 'capabilities used to filter interfaces.'
complete -c fi_info -s m -l mode --description 'to filter interfaces.'
complete -c fi_info -s t -l ep_type --description 'interface communication desired.'
complete -c fi_info -s a -l addr_format --description 'address format.'
complete -c fi_info -s p -l provider --description 'provider implementation.  For a list of providers, see the --list option.'
complete -c fi_info -s d -l domain --description 'the given domain name.'
complete -c fi_info -s f -l fabric --description 'the given fabric name.  Discovery.'
complete -c fi_info -s e -l env --description 'can be used to enable extra configuration or tuning.'
complete -c fi_info -s l -l list --description '.'
complete -c fi_info -s v -l verbose --description 'of each of the interfaces discovered.'
complete -c fi_info -l version --description 'USAGE EXAMPLES $ fi_info -n 30. 0. 11.'

