# fi_pingpong
# Autogenerated from man page /usr/share/man/man1/fi_pingpong.1.gz
complete -c fi_pingpong -s B --description 'control socket.'
complete -c fi_pingpong -s P --description 'the control socket.'
complete -c fi_pingpong -s p --description 'provider (e. g. , sockets, psm, usnic, etc. ).'
complete -c fi_pingpong -s e --description 'messaging between the two processes.'
complete -c fi_pingpong -s d --description 'Test Options.'
complete -c fi_pingpong -s I --description '.'
complete -c fi_pingpong -s S --description 'test will use or [aq]all[aq] to run all the default sizes.'
complete -c fi_pingpong -s c --description 'this will degrade performance).  Utility.'
complete -c fi_pingpong -s v --description '.'
complete -c fi_pingpong -s h --description 'USAGE EXAMPLES A simple example Server: fi_pingpong -p <provider_name>.'

