# libusb-config
# Autogenerated from man page /usr/share/man/man1/libusb-config.1.gz
complete -c libusb-config -l version --description 'Print the currently installed version of libusb on the standard output.'
complete -c libusb-config -l libs --description 'Print the linker flags that are necessary to link a libusb program.'
complete -c libusb-config -l cflags --description 'Print the compiler flags that are necessary to compile a libusb program.'
complete -c libusb-config -l prefix --description 'If specified, use PREFIX instead of the installation prefix that libusb was b…'
complete -c libusb-config -l exec-prefix --description 'If specified, use PREFIX instead of the installation exec prefix that libusb …'

