# oshcc
# Autogenerated from man page /usr/share/man/man1/oshcc.1.gz
complete -c oshcc -l showme --description 'This option comes in several different variants (see below).'
complete -c oshcc -l showme:compile --description 'Output the compiler flags that would have been supplied to the C compiler.'
complete -c oshcc -l showme:link --description 'Output the linker flags that would have been supplied to the C compiler.'
complete -c oshcc -l showme:command --description 'Outputs the underlying C compiler command (which may be one or more tokens).'
complete -c oshcc -l showme:incdirs --description 'Outputs a space-delimited (but otherwise undecorated) list of directories tha…'
complete -c oshcc -l showme:libdirs --description 'Outputs a space-delimited (but otherwise undecorated) list of directories tha…'
complete -c oshcc -l showme:libs --description 'Outputs a space-delimited (but otherwise undecorated) list of library names t…'
complete -c oshcc -l showme:version --description 'Outputs the version number of Open MPI.'
complete -c oshcc -l showme:help --description 'Output a brief usage help message.'
complete -c oshcc -o qfixed --description 'may be necessary to compile fixed-format Fortran source files.'
complete -c oshcc -o m64 --description 'build, but can be activated (for example, in a binary package providing both …'

