# oshmem_info
# Autogenerated from man page /usr/share/man/man1/oshmem_info.1.gz
complete -c oshmem_info -s a -l all --description 'Show all configuration options and MCA parameters.'
complete -c oshmem_info -l arch --description 'Show architecture Open MPI/SHMEM was compiled on.'
complete -c oshmem_info -s c -l config --description 'Show configuration options.'
complete -c oshmem_info -o gmca -l gmca --description 'Pass global MCA parameters that are applicable to all contexts.'
complete -c oshmem_info -s h -l help --description 'Shows help / usage message.'
complete -c oshmem_info -l hostname --description 'Show the hostname that Open MPI/SHMEM was configured and built on.'
complete -c oshmem_info -l internal --description 'Show internal MCA parameters (not meant to be modified by users).'
complete -c oshmem_info -l level --description 'Show only variables with at most this level (1-9).'
complete -c oshmem_info -o mca -l mca --description 'Pass context-specific MCA parameters; they are considered global if --gmca is…'
complete -c oshmem_info -l param --description 'Show MCA parameters.'
complete -c oshmem_info -l parsable --description 'When used in conjunction with other parameters, the output is displayed in a …'
complete -c oshmem_info -l path --description 'Show paths that Open MPI/SHMEM was configured with.'
complete -c oshmem_info -l pretty --description 'When used in conjunction with other parameters, the output is displayed in \'p…'
complete -c oshmem_info -l selected-only --description 'Show only variables from selected components.'
complete -c oshmem_info -l parseable --description 'Synonym for --parsable.'
complete -c oshmem_info -s V -l version --description 'Show version of Open MPI/SHMEM.  LEVELS.'

