# pngcheck
# Autogenerated from man page /usr/share/man/man1/pngcheck.1.gz
complete -c pngcheck -s 7 --description 'Print contents of text chunks, escape chars >=128 (for 7-bit terminals).'
complete -c pngcheck -s f --description 'Force continuation even after major errors.'
complete -c pngcheck -s p --description 'Display contents of \\s-1PLTE\\s0, tRNS, hIST, sPLT and \\s-1PPLT\\s0 (can be use…'
complete -c pngcheck -s q --description 'Test quietly (only output errors).'
complete -c pngcheck -s s --description 'Search for PNGs within another file.'
complete -c pngcheck -s t --description 'Display contents of tEXt chunks (can be used with -q).'
complete -c pngcheck -s v --description 'test verbosely (print most chunk data).'

