# pngsplit
# Autogenerated from man page /usr/share/man/man1/pngsplit.1.gz
complete -c pngsplit -l force --description 'Overwrite existing output files.'
complete -c pngsplit -l quiet --description 'Be quiet.'

