# presage_demo
# Autogenerated from man page /usr/share/man/man1/presage_demo.1.gz
complete -c presage_demo -s c -l config --description 'use config file CONFIG.'
complete -c presage_demo -s s -l suggestions --description 'set prediction size to N suggestions.'
complete -c presage_demo -s h -l help --description 'display this help and exit.'
complete -c presage_demo -s v -l version --description 'output version information and exit.'

