# presage_simulator
# Autogenerated from man page /usr/share/man/man1/presage_simulator.1.gz
complete -c presage_simulator -s c -l config --description 'use config file CONFIG.'
complete -c presage_simulator -s i -l insensitive --description 'case insensitive mode.'
complete -c presage_simulator -s q -l quiet --description 'quiet mode, no verbose output, same as silent.'
complete -c presage_simulator -s s -l silent --description 'silent mode, no verbose output, same as quiet.'
complete -c presage_simulator -s h -l help --description 'display this help and exit.'
complete -c presage_simulator -s v -l version --description 'output version information and exit.'

