# presage_demo_text
# Autogenerated from man page /usr/share/man/man1/presage_demo_text.1.gz
complete -c presage_demo_text -s c -l config --description 'use config file CONFIG.'
complete -c presage_demo_text -s s -l suggestions --description 'set prediction size to N suggestions.'
complete -c presage_demo_text -s h -l help --description 'display this help and exit.'
complete -c presage_demo_text -s v -l version --description 'output version information and exit.'

