# text2ngram
# Autogenerated from man page /usr/share/man/man1/text2ngram.1.gz
complete -c text2ngram -l output -s o --description 'Output file name O.'
complete -c text2ngram -l ngrams -s n --description 'Specify ngram cardinality N.'
complete -c text2ngram -l format -s f --description 'Output file format F: sqlite, tsv (tabbed separated values) .'
complete -c text2ngram -l append -s a --description 'Open output file in append mode.'
complete -c text2ngram -l help -s h --description 'Display this information.'
complete -c text2ngram -l lowercase -s l --description '.'
complete -c text2ngram -l version -s v --description 'Show version information.'

